'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class InsuranceCompany
    Public Property InsuranceCompanyID As Integer
    Public Property Name As String
    Public Property Shortname As String
    Public Property Address1 As String
    Public Property Address2 As String
    Public Property State As String
    Public Property Postcode As String
    Public Property Phone As String
    Public Property Email As String
    Public Property RecordStatusCodeID As Integer
    Public Property Created As Date
    Public Property LastModified As Date
    Public Property ParentInsuranceCompanyID As Integer
    Public Property CreditLimit As String
    Public Property StandardDiscount As Double
    Public Property ReportingCommitments As String
    Public Property BrandAssociations As String
    Public Property GiftCardLetter As String
    Public Property LetterHeads As String
    Public Property Notes As String

    Public Overridable Property RecordStatusCode As RecordStatusCode

    Public Overridable Property ParentInsuranceCompany As InsuranceCompany

    Public Overridable Property Quotes As ICollection(Of Quote) = New HashSet(Of Quote)

End Class
