'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Quote
    Public Property QuoteID As Integer
    Public Property InsuranceCompanyID As Integer
    Public Property ClaimNum As String
    Public Property StoreIDs As String
    Public Property CustomerName As String
    Public Property CustomerAddress1 As String
    Public Property CustomerAddress2 As String
    Public Property CustomerCity As String
    Public Property CustomerState As String
    Public Property CustomerPostcode As String
    Public Property CustomerPhone As String
    Public Property CustomerEmail As String
    Public Property CustomerDateOfBirth As Nullable(Of Date)
    Public Property NextOfKinName As String
    Public Property NextOfKinAddress1 As String
    Public Property NextOfKinAddress2 As String
    Public Property NextOfKinCity As String
    Public Property NextOfKinState As String
    Public Property NextOfKinPostcode As String
    Public Property NextOfKinPhone As String
    Public Property NextOfKinEmail As String
    Public Property NextOfKinDateOfBirth As Nullable(Of Date)
    Public Property CustomerContactAllowed As Nullable(Of Boolean)
    Public Property PolicyLimit As Nullable(Of Double)
    Public Property Created As Date
    Public Property LastModified As Date
    Public Property RecordStatusCodeID As Integer
    Public Property QuotePriority As String
    Public Property TeamMemberResponsible As String
    Public Property Notes As String
    Public Property FulfilmentMethod As String
    Public Property FulfilmentType As String
    Public Property PreferredBrands As String
    Public Property ClosestStores As String

    Public Overridable Property InsuranceCompany As InsuranceCompany
    Public Overridable Property RecordStatusCode As RecordStatusCode
    Public Overridable Property QuoteDetails As ICollection(Of QuoteDetail) = New HashSet(Of QuoteDetail)

End Class
