'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class QuoteStatusCode
    Public Property QuoteStatusCodeID As Integer
    Public Property Description As String
    Public Property Name As String
    Public Property RecordStatusCodeID As Integer
    Public Property Created As Date
    Public Property LastModified As Date

    Public Overridable Property QuoteStatusMaps As ICollection(Of QuoteStatusMap) = New HashSet(Of QuoteStatusMap)
    Public Overridable Property RecordStatusCode As RecordStatusCode

End Class
