'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class QuoteDetail
    Public Property QuoteDetailID As Integer
    Public Property QuoteID As Integer
    Public Property Quantity As String
    Public Property Created As Date
    Public Property LastModified As Date
    Public Property RecordStatusCodeID As Integer
    Public Property InsurerDescription As String
    Public Property OtherInformation As String
    Public Property PLU As String
    Public Property PLUDescription As String
    Public Property PLUQuantity As Nullable(Of Integer)
    Public Property PLUPrice As Nullable(Of Double)
    Public Property DiscountApplied As Nullable(Of Double)
    Public Property SRGBrandSupplying As String
    Public Property SRGStoreSupplying As String
    Public Property Comments As String
    Public Property Specialorder As Nullable(Of Boolean)
    Public Property Isapproved As Nullable(Of Boolean)

    Public Overridable Property Quote As Quote
    Public Overridable Property RecordStatusCode As RecordStatusCode

End Class
