'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RecordStatusCode
    Public Property RecordStatusCodeID As Integer
    Public Property Description As String
    Public Property Name As String
    Public Property MyRecordStatusID As Integer
    Public Property Created As Date
    Public Property LastModified As Date

    Public Overridable Property AuditTrails As ICollection(Of AuditTrail) = New HashSet(Of AuditTrail)
    Public Overridable Property InsuranceCompanies As ICollection(Of InsuranceCompany) = New HashSet(Of InsuranceCompany)
    Public Overridable Property Quotes As ICollection(Of Quote) = New HashSet(Of Quote)
    Public Overridable Property QuoteDetails As ICollection(Of QuoteDetail) = New HashSet(Of QuoteDetail)
    Public Overridable Property QuoteStatusCodes As ICollection(Of QuoteStatusCode) = New HashSet(Of QuoteStatusCode)
    Public Overridable Property QuoteStatusMaps As ICollection(Of QuoteStatusMap) = New HashSet(Of QuoteStatusMap)
    Public Overridable Property SRGBrands As ICollection(Of SRGBrand) = New HashSet(Of SRGBrand)

End Class
