'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SRGBrand
    Public Property SRGBrandID As Integer
    Public Property Name As String
    Public Property Shortname As String
    Public Property Created As Date
    Public Property LastModified As Date
    Public Property RecordStatusCodeID As Integer

    Public Overridable Property RecordStatusCode As RecordStatusCode

End Class
